// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlgzardmntredgfzjkla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sZ3phcmRtbnRyZWRnZnpqa2xhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDI0NTgsImV4cCI6MjA1OTYxODQ1OH0.HmwqeE7KWeUhiD_NauQGInR6WhpxkAkVZwNrsa6I-UY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);